---

- name: Installing pre-requisites
  package:
    name: unzip
    state: present

- name: Checking for installed ThinLinc packages
  block:
    - include_tasks: "check_installed_rpm.yml"
      when: ansible_os_family in ["RedHat", "Suse"]
    - include_tasks: "check_installed_deb.yml"
      when: ansible_os_family in ["Debian", "Ubuntu", "Linuxmint"]

- name: Installing ThinLinc packages
  block:
    - name: Unpacking ThinLinc server bundle
      unarchive:
        src: "{{ thinlinc_server_bundle }}"
        dest: /root
    - include_vars: "packages-rpm-{{ ansible_architecture }}.yml"
      when: ansible_os_family in ["RedHat", "Suse"]
    - include_vars: "packages-deb-{{ ansible_architecture }}.yml"
      when: ansible_os_family in ["Debian", "Ubuntu", "Linuxmint"]
    - include_tasks: "install-thinlinc-rhel.yml"
      when: ansible_os_family == "RedHat"
    - include_tasks: "install-thinlinc-suse.yml"
      when: ansible_os_family == "Suse"
    - include_tasks: "install-thinlinc-debian.yml"
      when: ansible_os_family in ["Debian", "Ubuntu", "Linuxmint"]
  when: thinlinc_packages_installed.rc == 1


- name: Copy in tlsetup.answers
  template:
    src: thinlinc-setup.answers.j2
    dest: /root/thinlinc-setup.answers
  notify: run tl-setup

# Force tl-setup to run here, if required
- meta: flush_handlers

- name: Configure /vsmagent/agent_hostname
  tlconfig:
    param: /vsmagent/agent_hostname
    value: "{{ thinlinc_agent_hostname or ansible_fqdn }}"
  notify: restart vsmagent
  when: "'thinlinc_agents' in group_names"

- name: Configure /vsmagent/master_hostname
  tlconfig:
    param: /vsmagent/master_hostname
    value: "{{ groups['thinlinc_masters'][0] or 'localhost' }}"
  notify: restart vsmagent
  when: "'thinlinc_agents' in group_names"

- name: Configure /vsmagent/allowed_clients
  tlconfig:
    param: /vsmagent/allowed_clients
    value: "{{ ' '.join(groups['thinlinc_masters']) or 'localhost' }}"
  notify: restart vsmagent
  when: "'thinlinc_agents' in group_names"

- name: Configure list of agent servers when thinlinc_use_cluster is true
  tlconfig:
    param: /vsmserver/subclusters/Default/agents
    value: "{{ ' '.join(groups['thinlinc_agents']) or 'localhost' }}"
  notify: restart vsmserver
  when:
    - "'thinlinc_masters' in group_names"
    - thinlinc_use_cluster

- name: Configure list of agent servers when thinlinc_use_cluster is false
  tlconfig:
    param: /vsmserver/subclusters/Default/agents
    value: "{{ ansible_fqdn }}"
  notify: restart vsmserver
  when: not thinlinc_use_cluster

- name: Set webaccess port to {{ thinlinc_webaccess_port }}
  tlconfig:
    param: /webaccess/listen_port
    value: "{{ thinlinc_webaccess_port }}"
  notify: restart tlwebaccess
